"$schema" = 'https://starship.rs/config-schema.json'
palette = 'everforest'
add_newline = true
command_timeout = 1000
format = """[╭─](muted)$os$username$hostname[ · ](muted)$directory$git_branch$git_status$git_state$fill$cmd_duration$time
[╰─](muted)$python$nodejs$rust$golang$dotnet$package$docker_context$jobs$status$character"""

[palettes.everforest]
sage = '#A7C080'
gold = '#DBBC7F'
cream = '#D3C6AA'
muted = '#859289'
aqua = '#83C092'
blue = '#7FBBB3'
rose = '#E67E80'
purple = '#D699B6'

[os]
disabled = false
style = 'sage'
format = '[$symbol]($style)'
[os.symbols]
Windows = '󰍲 '

[username]
show_always = true
style_user = 'bold cream'
style_root = 'bold rose'
format = '[$user]($style)'

[hostname]
ssh_only = true
format = '[@$hostname](blue)'

[directory]
style = 'bold sage'
format = '[ $path]($style)[$read_only](rose) '
truncation_length = 3
truncate_to_repo = true
truncation_symbol = '…/'
read_only = ' 󰌾'

[git_branch]
symbol = ' '
style = 'purple'
format = '[· ](muted)[$symbol$branch]($style) '

[git_status]
style = 'gold'
format = '([$all_status$ahead_behind]($style) )'
conflicted = '≠${count} '
ahead = '⇡${count} '
behind = '⇣${count} '
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
untracked = '?${count} '
modified = '~${count} '
staged = '+${count} '
deleted = '−${count} '
stashed = '󰆓${count} '

[git_state]
style = 'rose'
format = '[$state( $progress_current/$progress_total)]($style) '

[fill]
symbol = ' '

[cmd_duration]
min_time = 2000
style = 'gold'
format = '[󱎫 $duration]($style) [· ](muted)'

[time]
disabled = false
time_format = '%H:%M'
style = 'muted'
format = '[ $time]($style)'

[character]
success_symbol = '[❯](bold sage)'
error_symbol = '[❯](bold rose)'
vimcmd_symbol = '[❮](bold aqua)'

[status]
disabled = false
symbol = ' '
style = 'rose'
format = '[$symbol$status]($style) '

[jobs]
symbol = ' '
style = 'blue'
format = '[$symbol$number]($style) '

[python]
symbol = ' '
style = 'gold'
format = '[$symbol$version( $virtualenv)]($style) [· ](muted)'

[nodejs]
symbol = ' '
style = 'aqua'
format = '[$symbol$version]($style) [· ](muted)'

[rust]
symbol = ' '
style = 'rose'
format = '[$symbol$version]($style) [· ](muted)'

[golang]
symbol = ' '
style = 'blue'
format = '[$symbol$version]($style) [· ](muted)'

[dotnet]
symbol = ' '
style = 'purple'
format = '[$symbol$version]($style) [· ](muted)'

[package]
symbol = '󰏗 '
style = 'gold'
format = '[$symbol$version]($style) [· ](muted)'

[docker_context]
symbol = ' '
style = 'blue'
format = '[$symbol$context]($style) [· ](muted)'
