# Everforest Fusion / uosc 5.13.0
color=foreground=A7C080,foreground_text=232A2E,background=272E33,background_text=D3C6AA,window_border=475258,curtain=1E2326,success=A7C080,error=E67E80,match=DBBC7F,heatmap=7FBBB3
opacity=timeline=0.95,position=1,chapters=0.8,slider=0.95,slider_gauge=1,controls=0.9,speed=0.9,menu=0.98,submenu=0.55,border=1,title=0.95,tooltip=0.98,thumbnail=1,curtain=0.65,idle_indicator=0.85,audio_indicator=0.5,buffering_indicator=0.4,playlist_position=0.85,pause_indicator=0.85
controls=menu,gap,subtitles,audio,gap,space,speed,space,shuffle,loop-playlist,loop-file,gap,prev,play-pause,next,gap,items,fullscreen
controls_size=32
controls_margin=10
controls_spacing=4
timeline_style=bar
timeline_size=36
timeline_border=1
timeline_cache=yes
timeline_step=5
progress=windowed
progress_size=3
volume=right
volume_size=36
volume_step=2
menu_item_height=36
menu_min_width=320
menu_padding=8
menu_type_to_search=yes
top_bar=no-border
top_bar_size=40
top_bar_controls=right
top_bar_title=yes
window_border_size=1
border_radius=6
text_border=1
scale=1
scale_fullscreen=1.2
animation_duration=160
flash_duration=1200
proximity_in=50
proximity_out=160
pause_indicator=flash
chapter_ranges=openings:A7C08070,endings:DBBC7F70,ads:E67E8070
