# Everforest Fusion / uosc
MBTN_RIGHT script-binding uosc/menu
TAB script-binding uosc/toggle-ui
Ctrl+p script-binding uosc/playlist
Ctrl+o script-binding uosc/open-file
_ cycle pause #! Playback > Play / pause
_ seek -5 #! Playback > Back 5 seconds
_ seek 5 #! Playback > Forward 5 seconds
_ set speed 1 #! Playback > Normal speed
_ script-binding uosc/chapters #! Chapters
_ script-binding uosc/audio #! Audio tracks
_ script-binding uosc/subtitles #! Subtitles
_ script-binding uosc/playlist #! Playlist
_ script-binding uosc/open-file #! Open file
_ cycle fullscreen #! Fullscreen
